vindr:
  name: "vindr"
  data_type: "vindr_zs"
  data_dir: "${base.data_dir}"
  img_dir: "vindr-1.0.0-resized-1024"
  data_path: "vindr-1.0.0/breast-level_annotations.csv"
  text_max_length: ${base.text_max_length}