rsna_zs:
  name: "rsna"
  data_type: "image_classification"
  data_dir: "${base.data_dir}"
  img_dir: "data/rsna-breast-cancer-detection/RSNA_MAMMO_1080_JPG"
  data_path: "data/rsna-breast-cancer-detection/rsna_mammo_train.csv"
  text_max_length: ${base.text_max_length}
  data_frac: 1.0
  label_col: "cancer"